name: Node.js CI Build

on:
  push:
    branches: [main]
    paths:
      - "packages/**"
      - "tests/**"
      - "package-lock.json"
  pull_request: [main]
    paths:
      - "packages/**"
      - "tests/**"
      - "package-lock.json"

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16 # Need for npm >=7.7
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - run: npm test
